---
people:
  adee:
    - 132473526+adeeri@users.noreply.github.com
  addshore:
    - addshorewiki@gmail.com
    - adamshorland@gmail.com
    - addshore@users.noreply.github.com
    - adam.shorland@wikimedia.de
  arthur:
    - arthur.taylor@wikimedia.de
  bereket:
    - bereket.teshome@wikimedia.de
  cynthia:
    - cynthia.makonyango@wikimedia.de
  dan.shick:
    - dan.shick@wikimedia.de
  dat:
    - dat.nguyen@wikimedia.de
  deniz:
    - deniz.erdogan@wikimedia.de
  dima:
    - dima.koushha@wikimedia.de
  frederik:
    - frederik.ring@wikimedia.de
  guergana:
    - guergana.tzatchkova@wikimedia.de
  hasan:
    - hasan.akguen@wikimedia.de
  hanna:
    - 45200197+hanna-p-wmde@users.noreply.github.com
    - hanna.petruschat@wikimedia.de
  hoo:
    - hoo@online.de
    - mail@mariushoch.de
    - marius.hoch@wikimedia.de
  itamar:
    - itamar.givon@wikimedia.de
    - itamar.givon.dev@gmail.com
  jakob:
    - jakob.warkotsch@wikimedia.de
    - j.warkotsch@gmail.com
  jan.dittrich:
    - jan.dittrich@wikimedia.de
  ladsgroup:
    - ladsgroup@gmail.com
    - Ladsgroup@gmail.com
  loren:
    - loren.johnson@wikimedia.de
  lucas:
    - lucas.werkmeister@wikimedia.de
  michael:
    - michael.grosse@wikimedia.de
    - mic.grosse@googlemail.com
  muhammad:
    - muhammad.jaziraly@extern.wikimedia.de
    - muhammad.jaziraly@wikimedia.de
  noa:
    - noa.rave@wikimedia.de
  oliver:
    - oliver.shotton@wikimedia.de
    - outdooracorn@gmail.com
  quetzlcoatlus:
    - quetzlcoatlus@gmail.com
  raja:
    - 67963068+raja-wmde@users.noreply.github.com
  rosalie:
    - perside.rosalie@wikimedia.de
  rti:
    - rti@users.noreply.github.com
  sarai:
    - sarai.sanchez@wikimedia.de
  silvan:
    - silvan.heintze@wikimedia.de
    - 59574251+Silvan-WMDE@users.noreply.github.com
  tobias:
    - tobias.andersson@wikimedia.de
    - tobias.ande@gmail.com
  tom:
    - thomas.arrow_ext@wikimedia.de
    - tarrow@users.noreply.github.com
    - bomarrow1@gmail.com
    - thomasarrow@gmail.com
  tonina:
    - tonina.zhelyazkova@wikimedia.de
snapshots:
  2024-06-01:
    - quetzlcoatlus
    - dan.shick
    - guergana
    - hoo
    - itamar
    - tom
    - silvan
    - oliver
    - muhammad
    - jakob
    - lucas
    - noa
    - rosalie
    - sarai
    - dat
    - raja
    - hasan
    - deniz
    - arthur
    - dima
    - cynthia
    - loren
    - rti
    - adee
    - frederik
  2024-01-01: 
    - quetzlcoatlus
    - dan.shick
    - guergana
    - hoo
    - itamar
    - jakob
    - lucas
    - michael
    - noa
    - rosalie
    - sarai
    - silvan
    - tom
    - dat
    - raja
    - hasan
    - oliver
    - deniz
    - muhammad
    - arthur
    - loren
    - rti
    - adee
    - frederik
  2023-01-01: 
    - addshore
    - quetzlcoatlus
    - dan.shick
    - guergana
    - hoo
    - itamar
    - jakob
    - lucas
    - michael
    - noa
    - rosalie
    - sarai
    - silvan
    - tom
    - dat
    - raja
    - hasan
    - oliver
    - deniz
    - muhammad
  2022-01-01: 
    - addshore
    - quetzlcoatlus
    - dan.shick
    - guergana
    - hoo
    - itamar
    - jakob
    - jan.dittrich
    - lucas
    - michael
    - noa
    - rosalie
    - sarai
    - silvan
    - tom
    - tobias
    - dat
    - raja
    - hanna
    - oliver
    - deniz
  2021-01-01: 
    - addshore
    - quetzlcoatlus
    - bereket
    - dan.shick
    - guergana
    - hoo
    - itamar
    - jakob
    - jan.dittrich
    - ladsgroup
    - lucas
    - michael
    - noa
    - rosalie
    - sarai
    - silvan
    - tom
    - tobias
    - tonina
    - dat
    - raja
    - hanna
code:
  mwext-Wikibase: https://github.com/wikimedia/Wikibase.git
  mwext-Wikibase-sub-view-lib-value-view: https://gerrit.wikimedia.org/r/data-values/value-view
  mwext-Wikibase-sub-view-lib-wikibase-serialization: https://phabricator.wikimedia.org/source/wikibase-serialization.git
  mwext-Wikibase-sub-view-lib-datavalues-javascript: https://phabricator.wikimedia.org/source/datavalues-javascript.git
  mwext-Wikibase-sub-view-lib-wikibase-data-model: https://phabricator.wikimedia.org/source/wikibase-data-model.git
  mwext-Wikibase-sub-view-lib-wikibase-termbox: https://gerrit.wikimedia.org/r/wikibase/termbox
  mwext-Wikibase-sub-lib-wikibase-api: https://gerrit.wikimedia.org/r/wikibase/javascript-api
  mwext-WikibaseLexeme: https://github.com/wikimedia/mediawiki-extensions-WikibaseLexeme.git
  mwext-WikibaseQualityConstraints: https://github.com/wikimedia/mediawiki-extensions-WikibaseQualityConstraints.git
  mwext-WikibaseManifest: https://github.com/wikimedia/mediawiki-extensions-WikibaseManifest.git
  mwext-WikibaseMediaInfo: https://github.com/wikimedia/mediawiki-extensions-WikibaseMediaInfo.git
  mwext-WikibaseCirrusSearch: https://github.com/wikimedia/mediawiki-extensions-WikibaseCirrusSearch.git
  mwext-WikibaseLexemeCirrusSearch: https://github.com/wikimedia/mediawiki-extensions-WikibaseLexemeCirrusSearch.git
  mwext-ArticlePlaceholder: https://github.com/wikimedia/mediawiki-extensions-ArticlePlaceholder.git
  mwext-Cognate: https://github.com/wikimedia/mediawiki-extensions-Cognate.git
  mwext-InterwikiSorting: https://github.com/wikimedia/mediawiki-extensions-InterwikiSorting.git
  mwext-WikidataOrg: https://github.com/wikimedia/mediawiki-extensions-Wikidata.org.git
  mwext-WikibaseReconcileEdit: https://github.com/wmde/WikibaseReconcileEdit.git
  mwext-PropertySuggester: https://github.com/wikimedia/mediawiki-extensions-PropertySuggester.git
  gerrit-wb-property-suggester-scripts: https://gerrit.wikimedia.org/r/wikibase/property-suggester-scripts.git
  gerrit-purtle: https://gerrit.wikimedia.org/r/purtle.git
  gh-WikibaseDataModel: https://github.com/wmde/WikibaseDataModel.git
  gh-WikibaseDataModelServices: https://github.com/wmde/WikibaseDataModelServices.git
  gh-WikibaseDataModelSerialization: https://github.com/wmde/WikibaseDataModelSerialization.git
  gh-WikibaseInternalSerialization: https://github.com/wmde/WikibaseInternalSerialization.git
  gh-query-gui: https://gerrit.wikimedia.org/r/wikidata/query/gui
  gh-query-builder: https://gerrit.wikimedia.org/r/wikidata/query-builder
  gh-php-vuejs-templating: https://github.com/wmde/php-vuejs-templating.git
  gh-wikibase-release-pipeline: https://github.com/wmde/wikibase-release-pipeline.git
  gh-wikibase-docker: https://github.com/wmde/wikibase-docker.git
  gh-wikit: https://github.com/wmde/wikit.git
  gh-wikidata-mismatch-finder: https://github.com/wmde/wikidata-mismatch-finder
  gh-wikidata-wikibase-architecture: https://github.com/wmde/wikidata-wikibase-architecture
  gh-wikidata-wikibase-team: https://github.com/wmde/wikidata-wikibase-team
  gh-wbaas-deploy: https://github.com/wmde/wbaas-deploy
  gh-wbaas-backup: https://github.com/wmde/wbaas-backup
  gh-wikibase-cloud-status: https://github.com/wmde/wikibase-cloud-status
  gh-wdio-wikibase: https://github.com/wmde/wdio-wikibase
  gh-wikidata-item-quality-evaluator: https://github.com/wmde/wikidata-item-quality-evaluator
  gh-wikidata-constraints-violation-checker: https://github.com/wmde/wikidata-constraints-violation-checker
  gh-new-lexeme-special-page: https://github.com/wmde/new-lexeme-special-page
  gh-connecting-senses: https://github.com/wmde/connecting-senses
components:
  Repo:
    - mwext-Wikibase/repo/
    - gh-wdio-wikibase
  RepoFederatedProperties:
    - mwext-Wikibase/repo/includes/FederatedProperties
    - mwext-Wikibase/build/federated-properties
  RepoRestApi:
    - mwext-Wikibase/repo/rest-api
  RepoView:
    - mwext-Wikibase/view/
    - mwext-Wikibase-sub-view-
  Client:
    - mwext-Wikibase/client/
  Lib:
    - mwext-Wikibase/lib/
    - mwext-Wikibase-sub-lib-
  DataAccess:
    - mwext-Wikibase/data-access/
  Bridge:
    - mwext-Wikibase/client/data-bridge/
  Lexeme:
    - mwext-WikibaseLexeme/
    - gh-php-vuejs-templating/
    - gh-new-lexeme-special-page
    - gh-connecting-senses
  WikibaseReconcileEdit:
    - WikibaseReconcileEdit/
  QualityConstraints:
    - mwext-WikibaseQualityConstraints/
  ArticlePlaceholder:
    - mwext-ArticlePlaceholder/
  Cognate:
    - mwext-Cognate/
  InterwikiSorting:
    - mwext-InterwikiSorting/
  WikidataOrg:
    - mwext-WikidataOrg/
    - gh-wikidata-item-quality-evaluator
    - gh-wikidata-constraints-violation-checker
  PropertySuggester:
    - mwext-PropertySuggester/
    - gerrit-wb-property-suggester-scripts/
  Manifest:
    - mwext-WikibaseManifest/
  TermBox:
    - mwext-Wikibase-sub-view-lib-wikibase-termbox/
  QueryGui:
    - gh-query-gui/
  QueryBuilder:
    - gh-query-builder/
  DataModelLibs:
    - gh-WikibaseDataModel
    - gh-WikibaseInternal
  DesignSystem:
    - gh-wikit/
  Purtle:
    - gerrit-purtle/
  Releasing:
    - gh-wikibase-docker/
    - gh-wikibase-release-pipeline/
  Docs:
    - gh-wikidata-wikibase-architecture/
    - gh-wikidata-wikibase-team/
    - mwext-Wikibase/docs/
  MediaInfo:
    - mwext-WikibaseMediaInfo/
  MissmatchFinder:
    - gh-wikidata-mismatch-finder/
  Search:
    - mwext-WikibaseCirrusSearch/
    - mwext-WikibaseLexemeCirrusSearch/
  WikibaseCloud:
    - gh-wbaas-deploy/
    - gh-wbaas-backup
