---
people:
  abraham:
    start:
    end: 2021
    emails:
      - abraham.taherivand@wikimedia.de
  adee:
    start: 2023-05
    end: # Current
    emails:
      - 132473526+adeeri@users.noreply.github.com
  addshore:
    start: 2013
    end: 2023-06
    emails:
      - addshorewiki@gmail.com
      - adamshorland@gmail.com
      - addshore@users.noreply.github.com
      - adam.shorland@wikimedia.de
  adrian:
    start:
    end: 2016-09  # Last Wikibase commit https://github.com/wikimedia/mediawiki-extensions-Wikibase/commits?author=adrianheine
    emails:
      - adrian.heine@wikimedia.de
      - adrian.lang@wikimedia.de
  alaa:
    start:
    end: 2022 # Pretty sure by then
    emails:
      - alaa.sarhan@wikimedia.de
  aleksey:
    start:
    end: 2018-09
    emails:
      - aleksey.bekh-ivanov@wikimedia.de
  andrew:
    start:
    end: # Current
    emails:
      - andrew.kostka@wikimedia.de
  anja:
    start: 2012
    end: 2013-06
    emails:
      - anja.jentzsch@wikimedia.de
  arthur:
    start: 2023-12
    end: # Current
    emails:
      - arthur.taylor@wikimedia.de
  aude:
    start: 2012
    end: 2017-10  # Last Wikibase commit https://github.com/wikimedia/mediawiki-extensions-Wikibase/commits?author=filbertkm
    emails:
      - aude.wiki@gmail.com
  audrey:
    start: 2024-06
    end: # Current
    emails:
  benestar:
    start:
    end: 2017-02 # Last Wikibase commit https://github.com/wikimedia/mediawiki-extensions-Wikibase/commits?author=Benestar
    emails:
      - benestar.wikimedia@gmail.com
      - benestar.wikimedia@googlemail.com
  bereket:
    start:
    end: 2021-08
    emails:
      - bereket.teshome@wikimedia.de
  ckawohl:
    start:
    end: # Current
    emails:
      - 67744560+ckawohl-wmde@users.noreply.github.com
  cynthia:
    start: 2024-01
    end: # Current
    emails:
      - cynthia.makonyango@wikimedia.de
  dan.shick: 
    start:
    end: # Current
    emails:
      - dan.shick@wikimedia.de
  dat:
    start:
    end: # Current
    emails:
      - dat.nguyen@wikimedia.de
  daniel.kinzler:
    start:
    end: 2018-09 # Based on https://meta.wikimedia.org/w/index.php?title=User:DKinzler_(WMF)&oldid=18422316
    emails:
      - daniel.kinzler@wikimedia.de
  daniel.werner:
    start:
    end: 2013-12 # Based on Gerrit https://gerrit.wikimedia.org/r/q/owner:daniel.a.r.werner@gmail.com+status:merged
    emails:
      - daniel.werner@wikimedia.de
      - daniel.a.r.werner@gmail.com
  deniz:
    start: 2021-08
    end: # Current
    emails:
      - deniz.erdogan@wikimedia.de
  denny:
    start:
    end: 2013-09
    emails:
      - denny.vrandecic@wikimedia.de
  dima:
    start: 2024-01
    end: # Current
    emails:
      - dima.koushha@wikimedia.de
  frederik:
    start: 2023-01
    end: # Current
    emails:
      - frederik.ring@wikimedia.de
  frimelle:
    start:
    end: 2016-10
    emails:
      - lucie.kaffee@wikimedia.de
      - lucie.aimee@googlemail.com
  greta:
    start:
    end: 2019-06 # Based on gerrit https://gerrit.wikimedia.org/r/q/author:greta.doci@wikimedia.de
    emails:
      - greta.doci@wikimedia.de
  guergana:
    start:
    end: 2024-07
    emails:
      - guergana.tzatchkova@wikimedia.de
  hasan:
    start: 2022
    end: # Current
    emails:
      - hasan.akguen@wikimedia.de
  hanna:
    start:
    end: 2022-12
    emails:
      - 45200197+hanna-p-wmde@users.noreply.github.com
      - hanna.petruschat@wikimedia.de
  henning:
    start:
    end: 2015-10 # Based on gerrit https://gerrit.wikimedia.org/r/q/author:henning.snater@wikimedia.de
    emails:
      - henning.snater@wikimedia.de
  hoo:
    start:
    end: # Current
    emails:
      - hoo@online.de
      - mail@mariushoch.de
      - marius.hoch@wikimedia.de
  itamar:
    start:
    end: # Current
    emails:
      - itamar.givon@wikimedia.de
      - itamar.givon.dev@gmail.com
  jakob:
    start:
    end: # Current
    emails:
      - jakob.warkotsch@wikimedia.de
      - j.warkotsch@gmail.com
  jan.dittrich:
    start:
    end: 2022-08
    emails:
      - jan.dittrich@wikimedia.de
  jeblad:
    start:
    end: 2013-06
    emails:
      - john.blad@wikimedia.de
      - jeblad@gmail.com
  jens:
    start:
    end:
    emails:
      - jens.ohlig@wikimedia.de
  jeroen:
    start:
    end: 2019-06
    emails:
      - jeroendedauw@gmail.com
  joely:
    start: 2024-05
    end: # Current
    emails:
      - 
  jonas:
    start:
    end:
    emails:
      - jonas.kress@wikimedia.de
  ladsgroup:
    start:
    end: 2021-08
    emails:
      - ladsgroup@gmail.com
      - Ladsgroup@gmail.com
  leszek:
    start:
    end: # Current
    emails:
      - leszek.manicki@wikimedia.de
  loren:
    start: 2023-05
    end: # Current
    emails:
      - loren.johnson@wikimedia.de
  lucas:
    start:
    end: # Current
    emails:
      - lucas.werkmeister@wikimedia.de
  matthias:
    start:
    end: 2020-02  # Based on last gerrit merge https://gerrit.wikimedia.org/r/q/author:matthias.geisler@wikimedia.de
    emails:
      - matthias.geisler@wikimedia.de
  michael:
    start:
    end: 2024-03
    emails:
      - michael.grosse@wikimedia.de
      - mic.grosse@googlemail.com
  monica:
    start:
    end: # Current
    emails:
      - 50335264+darthmon@users.noreply.github.com
  muhammad:
    start: 2022-12
    end: # Current
    emails:
      - muhammad.jaziraly@extern.wikimedia.de
      - muhammad.jaziraly@wikimedia.de
  noa:
    start:
    end: # Current
    emails:
      - noa.rave@wikimedia.de
  oliver:
    start: 2021-11
    end: # Current
    emails:
      - oliver.shotton@wikimedia.de
      - outdooracorn@gmail.com
  pablo:
    start:
    end: 2020-11  # Last commit in Wikibase https://github.com/wikimedia/mediawiki-extensions-Wikibase/commits?author=wiese
    emails:
      - pablo.grass@wikimedia.de
  quetzlcoatlus:
    start:
    end: # Current
    emails:
      - quetzlcoatlus@gmail.com
  raja:
    start:
    end: # Current
    emails:
      - raja.amelung@wikimedia.de
      - 67963068+raja-wmde@users.noreply.github.com
  ricki:
    start:
    end: # Current
    emails:
      - 141253288+RickiJay-WMDE@users.noreply.github.com
  rosalie:
    start:
    end: # Current
    emails:
      - perside.rosalie@wikimedia.de
  rti:
    start: 2023-05
    end: # Current
    emails:
      - rti@users.noreply.github.com
  sarai:
    start:
    end: # Current
    emails:
      - sarai.sanchez@wikimedia.de
  silvan:
    start:
    end: # Current
    emails:
      - silvan.heintze@wikimedia.de
      - 59574251+Silvan-WMDE@users.noreply.github.com
  theimo:
    start:
    end: # Current
    emails:
      - thiemo.kreuz@wikimedia.de
      - thiemo.maettig@wikimedia.de
      - thiemowmde@users.noreply.github.com
  tobi:
    start:
    end: # Current
    emails:
      - tobias.gritschacher@wikimedia.de
  tobias:
    start:
    end: 2022
    emails:
      - tobias.andersson@wikimedia.de
      - tobias.ande@gmail.com
  tom:
    start:
    end: # Current
    emails:
      - thomas.arrow_ext@wikimedia.de
      - tarrow@users.noreply.github.com
      - bomarrow1@gmail.com
      - thomasarrow@gmail.com
  tonina:
    start:
    end: 2021-08
    emails:
      - tonina.zhelyazkova@wikimedia.de
snapshots:
  - 2024-06-01
  # Every year
  - 2024-01-01
  - 2023-01-01
  - 2022-01-01
  - 2021-01-01
  - 2020-01-01
  - 2019-01-01
  - 2018-01-01
  - 2017-01-01
  - 2016-01-01
  - 2015-01-01
  - 2014-01-01
  - 2013-01-01
  - 2012-01-01
code:
  mwext-Wikibase: https://github.com/wikimedia/Wikibase.git
  mwext-Wikibase-sub-view-lib-value-view: https://gerrit.wikimedia.org/r/data-values/value-view
  mwext-Wikibase-sub-view-lib-wikibase-serialization: https://phabricator.wikimedia.org/source/wikibase-serialization.git
  mwext-Wikibase-sub-view-lib-datavalues-javascript: https://phabricator.wikimedia.org/source/datavalues-javascript.git
  mwext-Wikibase-sub-view-lib-wikibase-data-model: https://phabricator.wikimedia.org/source/wikibase-data-model.git
  mwext-Wikibase-sub-view-lib-wikibase-termbox: https://gerrit.wikimedia.org/r/wikibase/termbox
  mwext-Wikibase-sub-lib-wikibase-api: https://gerrit.wikimedia.org/r/wikibase/javascript-api
  mwext-WikibaseLexeme: https://github.com/wikimedia/mediawiki-extensions-WikibaseLexeme.git
  mwext-WikibaseQualityConstraints: https://github.com/wikimedia/mediawiki-extensions-WikibaseQualityConstraints.git
  mwext-WikibaseManifest: https://github.com/wikimedia/mediawiki-extensions-WikibaseManifest.git
  mwext-WikibaseMediaInfo: https://github.com/wikimedia/mediawiki-extensions-WikibaseMediaInfo.git
  mwext-WikibaseCirrusSearch: https://github.com/wikimedia/mediawiki-extensions-WikibaseCirrusSearch.git
  mwext-WikibaseLexemeCirrusSearch: https://github.com/wikimedia/mediawiki-extensions-WikibaseLexemeCirrusSearch.git
  mwext-ArticlePlaceholder: https://github.com/wikimedia/mediawiki-extensions-ArticlePlaceholder.git
  mwext-Cognate: https://github.com/wikimedia/mediawiki-extensions-Cognate.git
  mwext-InterwikiSorting: https://github.com/wikimedia/mediawiki-extensions-InterwikiSorting.git
  mwext-WikidataOrg: https://github.com/wikimedia/mediawiki-extensions-Wikidata.org.git
  mwext-WikibaseReconcileEdit: https://github.com/wmde/WikibaseReconcileEdit.git
  mwext-PropertySuggester: https://github.com/wikimedia/mediawiki-extensions-PropertySuggester.git
  gerrit-wb-property-suggester-scripts: https://gerrit.wikimedia.org/r/wikibase/property-suggester-scripts.git
  gerrit-purtle: https://gerrit.wikimedia.org/r/purtle.git
  gh-WikibaseDataModel: https://github.com/wmde/WikibaseDataModel.git
  gh-WikibaseDataModelServices: https://github.com/wmde/WikibaseDataModelServices.git
  gh-WikibaseDataModelSerialization: https://github.com/wmde/WikibaseDataModelSerialization.git
  gh-WikibaseInternalSerialization: https://github.com/wmde/WikibaseInternalSerialization.git
  gh-query-gui: https://gerrit.wikimedia.org/r/wikidata/query/gui
  gh-query-builder: https://gerrit.wikimedia.org/r/wikidata/query-builder
  gh-php-vuejs-templating: https://github.com/wmde/php-vuejs-templating.git
  gh-wikibase-release-pipeline: https://github.com/wmde/wikibase-release-pipeline.git
  gh-wikibase-docker: https://github.com/wmde/wikibase-docker.git
  gh-wikit: https://github.com/wmde/wikit.git
  gh-wikidata-mismatch-finder: https://github.com/wmde/wikidata-mismatch-finder
  gh-wikidata-wikibase-architecture: https://github.com/wmde/wikidata-wikibase-architecture
  gh-wikidata-wikibase-team: https://github.com/wmde/wikidata-wikibase-team
  gh-wbaas-deploy: https://github.com/wmde/wbaas-deploy
  gh-wbaas-backup: https://github.com/wmde/wbaas-backup
  gh-wikibase-cloud-status: https://github.com/wmde/wikibase-cloud-status
  gh-wdio-wikibase: https://github.com/wmde/wdio-wikibase
  gh-wikidata-item-quality-evaluator: https://github.com/wmde/wikidata-item-quality-evaluator
  gh-wikidata-constraints-violation-checker: https://github.com/wmde/wikidata-constraints-violation-checker
  gh-new-lexeme-special-page: https://github.com/wmde/new-lexeme-special-page
  gh-connecting-senses: https://github.com/wmde/connecting-senses
components:
  Repo:
    - mwext-Wikibase/repo/
    - gh-wdio-wikibase
  RepoFederatedProperties:
    - mwext-Wikibase/repo/includes/FederatedProperties
    - mwext-Wikibase/build/federated-properties
  RepoRestApi:
    - mwext-Wikibase/repo/rest-api
  RepoView:
    - mwext-Wikibase/view/
    - mwext-Wikibase-sub-view-
  Client:
    - mwext-Wikibase/client/
  Lib:
    - mwext-Wikibase/lib/
    - mwext-Wikibase-sub-lib-
  DataAccess:
    - mwext-Wikibase/data-access/
  Bridge:
    - mwext-Wikibase/client/data-bridge/
  Lexeme:
    - mwext-WikibaseLexeme/
    - gh-php-vuejs-templating/
    - gh-new-lexeme-special-page
    - gh-connecting-senses
  WikibaseReconcileEdit:
    - WikibaseReconcileEdit/
  QualityConstraints:
    - mwext-WikibaseQualityConstraints/
  ArticlePlaceholder:
    - mwext-ArticlePlaceholder/
  Cognate:
    - mwext-Cognate/
  InterwikiSorting:
    - mwext-InterwikiSorting/
  WikidataOrg:
    - mwext-WikidataOrg/
    - gh-wikidata-item-quality-evaluator
    - gh-wikidata-constraints-violation-checker
  PropertySuggester:
    - mwext-PropertySuggester/
    - gerrit-wb-property-suggester-scripts/
  Manifest:
    - mwext-WikibaseManifest/
  TermBox:
    - mwext-Wikibase-sub-view-lib-wikibase-termbox/
  QueryGui:
    - gh-query-gui/
  QueryBuilder:
    - gh-query-builder/
  DataModelLibs:
    - gh-WikibaseDataModel
    - gh-WikibaseInternal
  DesignSystem:
    - gh-wikit/
  Purtle:
    - gerrit-purtle/
  Releasing:
    - gh-wikibase-docker/
    - gh-wikibase-release-pipeline/
  Docs:
    - gh-wikidata-wikibase-architecture/
    - gh-wikidata-wikibase-team/
    - mwext-Wikibase/docs/
  MediaInfo:
    - mwext-WikibaseMediaInfo/
  MissmatchFinder:
    - gh-wikidata-mismatch-finder/
  Search:
    - mwext-WikibaseCirrusSearch/
    - mwext-WikibaseLexemeCirrusSearch/
  WikibaseCloud:
    - gh-wbaas-deploy/
    - gh-wbaas-backup
