name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Go Build
      run: go build -v ./...

    - name: Go Test
      run: go test -v ./...


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Goxc Install
      run: go get github.com/laher/goxc

    - name: Goxc Build
      run: export VERSION=$(make githubversion) && export GOPATH=$(go env GOPATH) && make build

    - name: Goxc Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gox-build-output
        path: build

  run:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_version:
          - "18.09"
          - "19.03"
          - "20.10"
    steps:
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: ${{ matrix.docker_version }}
          docker_channel: stable

      - uses: actions/download-artifact@v2
        with:
          name: gox-build-output
          path: build

      - name: Extract executable
        run: |
          tar -xvf build/*/*amd64.tar.gz
          cp */gitanalysis .

      - name: Run gitanalysis commands
        run: |
          ./gitanalysis --version
          ./gitanalysis --help
          ./gitanalysis alpine echo Hello!
