name: Go Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Goxc Install
      run: go get github.com/laher/goxc

    - name: Goxc Build
      run: export VERSION=${{ steps.get_version.outputs.VERSION }} && export GOPATH=$(go env GOPATH) && make build

    - name: Goxc Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gox-build-output
        path: build

    - name: Create Github Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Github Release Assets
      id: upload-release-assets
      uses: dwenegar/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        release_id: ${{ steps.create_release.outputs.id }}
        assets_path: build/${{ steps.get_version.outputs.VERSION }}